CREATE TABLE IF NOT EXISTS `match` (
  `match_id` int(11) NOT NULL AUTO_INCREMENT,
  `alliance` varchar(4) NOT NULL,
  `matchNum` int(11) NOT NULL,
  `team` int(11) NOT NULL,
  `scout` varchar(20) NOT NULL,
  `autoDefence` varchar(20) NOT NULL,
  `breachDefence` varchar(20) NOT NULL,
  `highGoalAutoShotsMade` int(11) NOT NULL,
  `highGoalAutoMisses` int(11) NOT NULL,
  `lowGoalAutoShotsMade` int(11) NOT NULL,
  `lowGoalAutoMisses` int(11) NOT NULL,
  `categoryA` varchar(20) NOT NULL,
  `categoryAScore` int(11) NOT NULL,
  `categoryB` varchar(20) NOT NULL,
  `categoryBScore` int(11) NOT NULL,
  `categoryC` varchar(20) NOT NULL,
  `categoryCScore` int(11) NOT NULL,
  `categoryD` varchar(20) NOT NULL,
  `categoryDScore` int(11) NOT NULL,
  `lowBarScore` int(11) NOT NULL,
  `lowGoalShots` int(11) NOT NULL,
  `missedLowGoalShots` int(11) NOT NULL,
  `highGoalShots` int(11) NOT NULL,
  `missedHighGoalShots` int(11) NOT NULL,
  `challengeTower` varchar(20) NOT NULL,
  `scaleTower` varchar(20) NOT NULL,
  `fouls` int(11) NOT NULL,
  `techFouls` int(11) NOT NULL,
  `redCard` varchar(20) NOT NULL,
  `yellowCard` varchar(20) NOT NULL,
  `comments` varchar(255) NOT NULL,
  PRIMARY KEY (`match_id`),
  UNIQUE KEY `match_id` (`match_id`),
  KEY `alliance` (`alliance`,`matchNum`,`team`,`scout`,`autoDefence`,`breachDefence`,`categoryA`,`categoryB`,`categoryC`,`categoryD`,`challengeTower`,`scaleTower`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

